### ISSUE TITLE
Unable to plot the graph.

### ISSUE THREAD

**Issue by dhnirshad** [wallnerryan/matplotlib-utils-cosbench#1]
matplotlib-utils-cosbench showing error on executing the below command-

matplotlib-utils-cosbench-master# python graph_data_throughput.py s3-main.csv

Below is the error list-
Traceback (most recent call last):
  File "graph_data_throughput.py", line 48, in <module>
    fig.savefig("./figures/%s_%s.png" % (str(**file**), s))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2211, in print_figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 526, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: './figures/graph_data_throughput.py_s3-main.csv.png'

**Comment by wallnerryan** [comment]
This error is saying there is no "figures" directory in the source of the scripts.

try

```
cd matplotlib-utils-cosbench/
mkdir figures/
```

Then retry your input.
